### ISSUE TITLE
Auto closing of all bookmark directories

### ISSUE THREAD

**Issue by julienfroidefond** [julienfroidefond/strapi-bookmarks#35]
When strapi bookmarks is activated, every other directory opened by click are closing up !

**Comment by dalexanco** [comment]
Solutions :

**naive one : detect if no changes available**
Simply compare both bookmarks tree (local & backend) to say if changes are available, if not, stop sync

**more complex / complete solution**
Compare both tree and only apply changes (create/delete/update of nodes)
