### ISSUE TITLE
jwt token => oAuth

### ISSUE THREAD

**Issue by julienfroidefond** [julienfroidefond/strapi-bookmarks#48]
Users should login to the extension to access to bookmarks
Quid oAuth2

**Comment by julienfroidefond** [comment]
@dalexanco not sure token unique system is not the right thing => https://strapi.io/documentation/developer-docs/latest/guides/api-token.html#introduction

**Comment by dalexanco** [comment]
> @dalexanco not sure token unique system is not the right thing => https://strapi.io/documentation/developer-docs/latest/guides/api-token.html#introduction
> 

Yeah, it seems good, so I suggest to set a low priority on this one for now.
Let handle login/pass only if we have deprectated token issues in the futur..

**Comment by julienfroidefond** [comment]
`if we have deprectated token issues in the futur..`
LOL you are Nostradamus
